services:
  # eudi verifier using direct_post (no encryption) as the response_mode
  eudi_verifier:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt:v0.5.1
    container_name: eudi_verifier
    ports:
      - "8080:8080"
    volumes:
      - ./testdata/eudi/verifier/keystore.p12:/keystore.p12
    environment:
      - VERIFIER_RESPONSE_MODE="DirectPost"
      - VERIFIER_PUBLIC_URL="0.0.0.0:8080"
      - VERIFIER_CLIENTIDSCHEME=x509_san_dns
      - VERIFIER_JAR_SIGNING_KEY=LoadFromKeystore
      - VERIFIER_JAR_SIGNING_KEY_ALIAS=verifier_cert
      - VERIFIER_JAR_SIGNING_KEY_KEYSTORE=file:///keystore.p12
      - VERIFIER_JAR_SIGNING_KEY_KEYSTORE_PASSWORD=changeit
      - VERIFIER_JAR_SIGNING_KEY_KEYSTORE_TYPE=pkcs12
      - VERIFIER_JAR_SIGNING_KEY_PASSWORD=changeit
      - VERIFIER_VALIDATION_SDJWTVC_STATUSCHECK_ENABLED=false
      - VERIFIER_ORIGINALCLIENTID=localhost


  # eudi verifier using direct_post.jwt (with encryption) as the response_mode
  # eudi_verifier_jwt:
  #   image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt:edge
  #   container_name: eudi_verifier_jwt
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - VERIFIER_RESPONSE_MODE="DirectPostJwt"
  #     - VERIFIER_PUBLIC_URL="0.0.0.0:8081"
  #     - SERVER_PORT=8081

  custom_verifier_frontend:
    build: ./eudi_demo_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./eudi_demo_frontend:/app
      - /app/node_modules

  # eudi_verifier_fontend:
  #   image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
  #   container_name: verifier_frontend
  #   ports:
  #     - "4300:4300"
  #   environment:
  #     - DOMAIN_NAME=""
  #     - HOST_API="http://localhost:8080"
  #
